pipeline {

    agent any

    environment {
        ARTIFACTORY_ID = 'localjfrog'
    }

    stages {

        stage('Clone repository') {
            steps {
                git branch: 'master', url: "https://github.com/claudiodornelles/calculator-app.git"
            }
        }

        stage('Test application') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Build application') {
            steps {
                sh './gradlew build'
            }
        }

        stage('Publish artifactory') {
            steps {
                rtServer (id: env.ARTIFACTORY_ID)
                rtUpload (
                    serverId: env.ARTIFACTORY_ID,
                    spec: """{
                                "files": [
                                    {
                                        "pattern": "build/libs/calculator.war",
                                        "target": "calculator-app"
                                    }
                                ]
                    }"""
                )
            }
        }
    }
}