pipeline {
    def jfrogInstance = JFrog.instance SERVER_ID
    def rtServer = jfrogInstance.artifactory

    agent any

    stages {

        stage('Clone repository') {
            steps {
                git branch: 'master', url: "https://github.com/claudiodornelles/calculator-app.git"
            }
        }

        stage('Test application') {
            steps {
                sh './gradlew test'
            }
        }

        stage('Build application') {
            steps {
                sh './gradlew build'
            }
        }

        stage('Publish artifactory') {
            steps {
                rtServer.upload spec: """{
                                            "files": [
                                                {
                                                    "pattern": "build/libs/calculator.war",
                                                    "target": "calculator-app"
                                                }
                                            ]
                                      }"""
            }
        }

    }
}